# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode 15
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15
    - name: Build (macOS)
      run: swift build -v --package-path QuintKit
    - name: Test (macOS)
      run: swift test -v --package-path QuintKit
  
  ios:
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - ios-version: '13.0'
            device: 'iPhone 11'
          - ios-version: '14.0'
            device: 'iPhone 12'
          - ios-version: '15.0'
            device: 'iPhone 13'
          - ios-version: '16.0'
            device: 'iPhone 14'
          - ios-version: '17.0'
            device: 'iPhone 15'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode 15
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15
    - name: Build (iOS)
      run: xcodebuild build -scheme QuintKit -sdk iphoneos -destination 'generic/platform=iOS,OS=${{ matrix.ios-version }}'
      working-directory: QuintKit
    - name: Test (iOS)
      run: xcodebuild test -scheme QuintKitTests -sdk iphoneos -destination 'platform=iOS Simulator,OS=${{ matrix.ios-version }},name=${{ matrix.device }}'
      working-directory: QuintKit

  tvos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode 15
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15
    - name: Build (tvOS)
      run: xcodebuild build -scheme QuintKit -sdk appletvos -destination 'generic/platform=tvOS'
      working-directory: QuintKit
    - name: Test (tvOS)
      run: xcodebuild test -scheme QuintKitTests -sdk appletvos -destination 'platform=tvOS Simulator,name=Apple TV'
      working-directory: QuintKit

  watchos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode 15
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15
    - name: Build (watchOS)
      run: xcodebuild build -scheme QuintKit -sdk watchos -destination 'generic/platform=watchOS'
      working-directory: QuintKit
    # Tests are not supported on watchOS
